version: '2'

services:
  memcache:
    image: memcached:1.4.25

  redis-master:
    image: redis:3.2.0

  redis-slave:
    image: redis:3.2.0
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
